// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingentity"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BillingEntityUpdate is the builder for updating BillingEntity entities.
type BillingEntityUpdate struct {
	config
	hooks    []Hook
	mutation *BillingEntityMutation
}

// Where appends a list predicates to the BillingEntityUpdate builder.
func (_u *BillingEntityUpdate) Where(ps ...predicate.BillingEntity) *BillingEntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingEntityUpdate) SetUpdatedAt(v time.Time) *BillingEntityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *BillingEntityUpdate) SetName(v string) *BillingEntityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BillingEntityUpdate) SetNillableName(v *string) *BillingEntityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BillingEntityUpdate) SetCurrency(v string) *BillingEntityUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BillingEntityUpdate) SetNillableCurrency(v *string) *BillingEntityUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingEntityUpdate) SetStatus(v string) *BillingEntityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingEntityUpdate) SetNillableStatus(v *string) *BillingEntityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *BillingEntityUpdate) AddUserIDs(ids ...int64) *BillingEntityUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *BillingEntityUpdate) AddUsers(v ...*User) *BillingEntityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the BillingEntityMutation object of the builder.
func (_u *BillingEntityUpdate) Mutation() *BillingEntityMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *BillingEntityUpdate) ClearUsers() *BillingEntityUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *BillingEntityUpdate) RemoveUserIDs(ids ...int64) *BillingEntityUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *BillingEntityUpdate) RemoveUsers(v ...*User) *BillingEntityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillingEntityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillingEntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingEntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingEntityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingEntityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := billingentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := billingentity.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingEntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingentity.Table, billingentity.Columns, sqlgraph.NewFieldSpec(billingentity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(billingentity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(billingentity.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingentity.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillingEntityUpdateOne is the builder for updating a single BillingEntity entity.
type BillingEntityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillingEntityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingEntityUpdateOne) SetUpdatedAt(v time.Time) *BillingEntityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *BillingEntityUpdateOne) SetName(v string) *BillingEntityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BillingEntityUpdateOne) SetNillableName(v *string) *BillingEntityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BillingEntityUpdateOne) SetCurrency(v string) *BillingEntityUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BillingEntityUpdateOne) SetNillableCurrency(v *string) *BillingEntityUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BillingEntityUpdateOne) SetStatus(v string) *BillingEntityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BillingEntityUpdateOne) SetNillableStatus(v *string) *BillingEntityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *BillingEntityUpdateOne) AddUserIDs(ids ...int64) *BillingEntityUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *BillingEntityUpdateOne) AddUsers(v ...*User) *BillingEntityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the BillingEntityMutation object of the builder.
func (_u *BillingEntityUpdateOne) Mutation() *BillingEntityMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *BillingEntityUpdateOne) ClearUsers() *BillingEntityUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *BillingEntityUpdateOne) RemoveUserIDs(ids ...int64) *BillingEntityUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *BillingEntityUpdateOne) RemoveUsers(v ...*User) *BillingEntityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the BillingEntityUpdate builder.
func (_u *BillingEntityUpdateOne) Where(ps ...predicate.BillingEntity) *BillingEntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillingEntityUpdateOne) Select(field string, fields ...string) *BillingEntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillingEntity entity.
func (_u *BillingEntityUpdateOne) Save(ctx context.Context) (*BillingEntity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingEntityUpdateOne) SaveX(ctx context.Context) *BillingEntity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillingEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingEntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingEntityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillingEntityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := billingentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := billingentity.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := billingentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BillingEntityUpdateOne) sqlSave(ctx context.Context) (_node *BillingEntity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billingentity.Table, billingentity.Columns, sqlgraph.NewFieldSpec(billingentity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillingEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingentity.FieldID)
		for _, f := range fields {
			if !billingentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billingentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(billingentity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(billingentity.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(billingentity.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BillingEntity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
