// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/billingentity"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BillingEntityCreate is the builder for creating a BillingEntity entity.
type BillingEntityCreate struct {
	config
	mutation *BillingEntityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingEntityCreate) SetCreatedAt(v time.Time) *BillingEntityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingEntityCreate) SetNillableCreatedAt(v *time.Time) *BillingEntityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingEntityCreate) SetUpdatedAt(v time.Time) *BillingEntityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingEntityCreate) SetNillableUpdatedAt(v *time.Time) *BillingEntityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *BillingEntityCreate) SetName(v string) *BillingEntityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BillingEntityCreate) SetCurrency(v string) *BillingEntityCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BillingEntityCreate) SetStatus(v string) *BillingEntityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BillingEntityCreate) SetNillableStatus(v *string) *BillingEntityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *BillingEntityCreate) AddUserIDs(ids ...int64) *BillingEntityCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *BillingEntityCreate) AddUsers(v ...*User) *BillingEntityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the BillingEntityMutation object of the builder.
func (_c *BillingEntityCreate) Mutation() *BillingEntityMutation {
	return _c.mutation
}

// Save creates the BillingEntity in the database.
func (_c *BillingEntityCreate) Save(ctx context.Context) (*BillingEntity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingEntityCreate) SaveX(ctx context.Context) *BillingEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingEntityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := billingentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := billingentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := billingentity.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingEntityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillingEntity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingEntity.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BillingEntity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := billingentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BillingEntity.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := billingentity.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BillingEntity.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := billingentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BillingEntity.status": %w`, err)}
		}
	}
	return nil
}

func (_c *BillingEntityCreate) sqlSave(ctx context.Context) (*BillingEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingEntityCreate) createSpec() (*BillingEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingentity.Table, sqlgraph.NewFieldSpec(billingentity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(billingentity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(billingentity.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(billingentity.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billingentity.UsersTable,
			Columns: []string{billingentity.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingEntity.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingEntityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingEntityCreate) OnConflict(opts ...sql.ConflictOption) *BillingEntityUpsertOne {
	_c.conflict = opts
	return &BillingEntityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingEntityCreate) OnConflictColumns(columns ...string) *BillingEntityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingEntityUpsertOne{
		create: _c,
	}
}

type (
	// BillingEntityUpsertOne is the builder for "upsert"-ing
	//  one BillingEntity node.
	BillingEntityUpsertOne struct {
		create *BillingEntityCreate
	}

	// BillingEntityUpsert is the "OnConflict" setter.
	BillingEntityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingEntityUpsert) SetUpdatedAt(v time.Time) *BillingEntityUpsert {
	u.Set(billingentity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingEntityUpsert) UpdateUpdatedAt() *BillingEntityUpsert {
	u.SetExcluded(billingentity.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *BillingEntityUpsert) SetName(v string) *BillingEntityUpsert {
	u.Set(billingentity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BillingEntityUpsert) UpdateName() *BillingEntityUpsert {
	u.SetExcluded(billingentity.FieldName)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BillingEntityUpsert) SetCurrency(v string) *BillingEntityUpsert {
	u.Set(billingentity.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BillingEntityUpsert) UpdateCurrency() *BillingEntityUpsert {
	u.SetExcluded(billingentity.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *BillingEntityUpsert) SetStatus(v string) *BillingEntityUpsert {
	u.Set(billingentity.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingEntityUpsert) UpdateStatus() *BillingEntityUpsert {
	u.SetExcluded(billingentity.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingEntityUpsertOne) UpdateNewValues() *BillingEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingentity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingEntityUpsertOne) Ignore() *BillingEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingEntityUpsertOne) DoNothing() *BillingEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingEntityCreate.OnConflict
// documentation for more info.
func (u *BillingEntityUpsertOne) Update(set func(*BillingEntityUpsert)) *BillingEntityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingEntityUpsertOne) SetUpdatedAt(v time.Time) *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingEntityUpsertOne) UpdateUpdatedAt() *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *BillingEntityUpsertOne) SetName(v string) *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BillingEntityUpsertOne) UpdateName() *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateName()
	})
}

// SetCurrency sets the "currency" field.
func (u *BillingEntityUpsertOne) SetCurrency(v string) *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BillingEntityUpsertOne) UpdateCurrency() *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *BillingEntityUpsertOne) SetStatus(v string) *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingEntityUpsertOne) UpdateStatus() *BillingEntityUpsertOne {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *BillingEntityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingEntityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingEntityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingEntityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingEntityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingEntityCreateBulk is the builder for creating many BillingEntity entities in bulk.
type BillingEntityCreateBulk struct {
	config
	err      error
	builders []*BillingEntityCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingEntity entities in the database.
func (_c *BillingEntityCreateBulk) Save(ctx context.Context) ([]*BillingEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingEntityCreateBulk) SaveX(ctx context.Context) []*BillingEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingEntity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingEntityUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingEntityCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingEntityUpsertBulk {
	_c.conflict = opts
	return &BillingEntityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingEntityCreateBulk) OnConflictColumns(columns ...string) *BillingEntityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingEntityUpsertBulk{
		create: _c,
	}
}

// BillingEntityUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingEntity nodes.
type BillingEntityUpsertBulk struct {
	create *BillingEntityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BillingEntityUpsertBulk) UpdateNewValues() *BillingEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingentity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingEntity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingEntityUpsertBulk) Ignore() *BillingEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingEntityUpsertBulk) DoNothing() *BillingEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingEntityCreateBulk.OnConflict
// documentation for more info.
func (u *BillingEntityUpsertBulk) Update(set func(*BillingEntityUpsert)) *BillingEntityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingEntityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingEntityUpsertBulk) SetUpdatedAt(v time.Time) *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingEntityUpsertBulk) UpdateUpdatedAt() *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *BillingEntityUpsertBulk) SetName(v string) *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *BillingEntityUpsertBulk) UpdateName() *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateName()
	})
}

// SetCurrency sets the "currency" field.
func (u *BillingEntityUpsertBulk) SetCurrency(v string) *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BillingEntityUpsertBulk) UpdateCurrency() *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *BillingEntityUpsertBulk) SetStatus(v string) *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BillingEntityUpsertBulk) UpdateStatus() *BillingEntityUpsertBulk {
	return u.Update(func(s *BillingEntityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *BillingEntityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingEntityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingEntityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingEntityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
